"""
Exploratory Data Analysis (EDA) for the synthetic fraud‑detection dataset.

This script reads a CSV file produced by `generate_data.py` and computes basic
summary statistics.  It also creates simple visualisations to help
understand the relationships between the features and the multiple target
variables.  All plots are created with matplotlib and saved to a
`plots/` subdirectory relative to the working directory.
"""

import argparse
import os
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def run_eda(data_path: str) -> None:
    """Perform exploratory data analysis on the dataset at `data_path`.

    Parameters
    ----------
    data_path : str
        Path to the CSV file containing the synthetic transaction data.
    """
    df = pd.read_csv(data_path)

    # Display basic information
    print("Data dimensions:", df.shape)
    print("\nColumn types:\n", df.dtypes)
    print("\nFirst 5 rows:\n", df.head())

    # Summary statistics
    print("\nSummary statistics:\n", df.describe())

    # Ensure plots directory exists
    plots_dir = Path("plots")
    plots_dir.mkdir(exist_ok=True)

    # Correlation heatmap for all numeric variables
    corr = df.corr(numeric_only=True)
    fig, ax = plt.subplots(figsize=(10, 8))
    cax = ax.imshow(corr)
    ax.set_title("Correlation Matrix")
    ax.set_xticks(range(len(corr.columns)))
    ax.set_yticks(range(len(corr.columns)))
    ax.set_xticklabels(corr.columns, rotation=90)
    ax.set_yticklabels(corr.columns)
    fig.colorbar(cax)
    fig.tight_layout()
    heatmap_path = plots_dir / "correlation_heatmap.png"
    plt.savefig(heatmap_path)
    plt.close(fig)
    print(f"Correlation heatmap saved to {heatmap_path}")

    # Distribution of binary target variables
    target_cols = [
        "fraud_label",
        "chargeback_label",
        "takeover_label",
    ]
    for col in target_cols:
        counts = df[col].value_counts().sort_index()
        fig, ax = plt.subplots()
        ax.bar(counts.index.astype(str), counts.values)
        ax.set_title(f"Distribution of {col}")
        ax.set_xlabel(col)
        ax.set_ylabel("Count")
        dist_path = plots_dir / f"{col}_distribution.png"
        plt.savefig(dist_path)
        plt.close(fig)
        print(f"Saved distribution plot for {col} to {dist_path}")

    # Histogram for anomaly score
    fig, ax = plt.subplots()
    ax.hist(df["anomaly_score"], bins=30)
    ax.set_title("Distribution of anomaly_score")
    ax.set_xlabel("anomaly_score")
    ax.set_ylabel("Frequency")
    anomaly_path = plots_dir / "anomaly_score_histogram.png"
    plt.savefig(anomaly_path)
    plt.close(fig)
    print(f"Saved histogram of anomaly_score to {anomaly_path}")


def main():
    parser = argparse.ArgumentParser(description="Perform EDA on the synthetic fraud‑detection dataset.")
    parser.add_argument(
        "--data",
        type=str,
        default="data/transactions.csv",
        help="Path to the CSV file generated by generate_data.py.",
    )
    args = parser.parse_args()
    run_eda(args.data)


if __name__ == "__main__":
    main()
